replicaCount: 1

image:
  repository: tiangolo/python3.9
  tag: "latest"
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: flask-app.local
      paths:
        - path: /
          pathType: Prefix

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 80

# Specify the command to run the Flask app
command:
  - "flask"
args:
  - "run"
  - "--host=0.0.0.0"
  - "--port=80"