replicaCount: 1

image:
  repository: python
  tag: "3.9-slim"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: "traefik"   # Specify Traefik as the ingress class
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router-entrypoints: "web"  # Traefik HTTP entrypoint
  hosts:
    - host: ""  # Replace with your domain
      paths:
        - path: /
          pathType: Prefix
  tls: []