apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-flask-app.fullname" . }}
  labels:
    app: {{ include "my-flask-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-flask-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-flask-app.name" . }}
    spec:
      containers:
        - name: flask-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: FLASK_APP
              value: app.py
            - name: FLASK_ENV
              value: development
          command: ["flask", "run", "--host=0.0.0.0", "--port=8080"]
      resources:
        limits:
          cpu: {{ .Values.resources.limits.cpu }}
          memory: {{ .Values.resources.limits.memory }}
        requests:
          cpu: {{ .Values.resources.requests.cpu }}
          memory: {{ .Values.resources.requests.memory }}
      nodeSelector: {{ .Values.nodeSelector }}
      tolerations: {{ toYaml .Values.tolerations | indent 8 }}
      affinity: {{ toYaml .Values.affinity | indent 8 }}
