apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-flask-app.fullname" . }}
  labels:
    app: {{ include "my-flask-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-flask-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-flask-app.name" . }}
    spec:
      containers:
      - name: flask-app
        image: "python:3.9-slim"  # Use the official Python image
        command: [ "python", "/app/app.py" ]  # Run the Flask app
        volumeMounts:
        - name: flask-app-code   # Referencing the correct volume by name
          mountPath: /app        # Mount the ConfigMap at /app path
        ports:
        - containerPort: 5000
      volumes:                    # Ensure the volume is defined properly
      - name: flask-app-code
        configMap:
          name: my-flask-app-config   # Reference the correct ConfigMap
