apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-flask-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-flask-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-flask-app.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "python:3.10-slim"  # Using a lightweight Python image
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: flask-app-volume
              mountPath: /app  # Mount it to the working directory
          command: ["python", "/app/app.py"]  # Command to run your Flask app
      volumes:
        - name: flask-app-volume
          configMap:
            name: flask-app-config
