apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-flask-app.fullname" . }}
  labels:
    app: {{ include "my-flask-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-flask-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-flask-app.name" . }}
    spec:
      containers:
      - name: flask-app
        image: "python:3.9-slim"  # Using the official Python image
        command: ["/bin/sh", "-c"] # Use shell to run multiple commands
        args:
          - |
            pip install -r /app/requirements.txt &&  # Install dependencies
            python /app/app.py  # Run the Flask app
        volumeMounts:
        - name: flask-app-code   # Reference the correct volume
          mountPath: /app        # Mount the ConfigMap at /app path
        ports:
        - containerPort: 5000
      volumes:
      - name: flask-app-code
        configMap:
          name: my-flask-app-config   # Reference the correct ConfigMap
