{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "my-flask-app.fullname" . }}
  labels:
    app: {{ include "my-flask-app.name" . }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}  # Accessing host correctly
      http:
        paths:
          - path: /  # Accessing path directly
            pathType: Prefix  # Accessing pathType directly
            backend:
              service:
                name: {{ include "my-flask-app.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
